### ISSUE TITLE
Can we move this to the ZMON org?

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando-stups/zmon-entity-adapter#5]
cc @Jan-M

**Comment by hjacobs** [comment]
No, this is the adapter between STUPS and ZMON (it pushed STUPS entities such as Kio applications to ZMON) --- i.e. it does not belong to ZMON, but to STUPS.

**Comment by LappleApple** [comment]
OK

**Comment by lasomethingsomething** [comment]
OK... is the maintainers file current?

**Comment by hjacobs** [comment]
Yes, I think so (@tuxlife is on vacation)
